version: '3.9'

services:
  flask_app:
    build: flaskr
    container_name: flask_app
    restart: always
    volumes:
      - ./flaskr:/usr/src/flaskr
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - es


  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust


  es:
    image: elasticsearch:7.13.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - es_volume:/var/lib/elasticsearch/data/
    env_file:
      - .env
    ports:
      - "9200:9200"


volumes:
  postgres_volume:
  es_volume:
