version: '3.9'

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - es

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - flask_app

  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  es:
    image: elasticsearch:7.13.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - es_volume:/var/lib/elasticsearch/data/
    env_file:
      - .env
    ports:
      - "9200:9200"
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: "1s"
      timeout: "3s"
      retries: 60


volumes:
  postgres_volume:
  es_volume:
