"""empty message

Revision ID: 765e59f7e5f1
Revises: 5416707800af
Create Date: 2021-07-12 22:09:36.129089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765e59f7e5f1'
down_revision = '5416707800af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
